const conexionDB = require('../../conexionDB.js');
const { chequearExistenciaTablaSimple } = require('./loadUtils.js');

async function cargaDatosDePruebaTablaProductos()
{
    console.log('Cargando datos de prueba a la tabla productos');

    const productos = [
        { nombre: 'Manzanas Rojas',          descripcion: 'Frescas y crujientes, directo del campo.',                       fuenteImagen: '/images/productos/manzana roja.webp',                precio: 1200,       categoria: 'Comida',     subcategoria: 'Frutas',                 activo: 1,      valoracion_promedio: 0.00,      cantidad_valoraciones: 0,       cantidad_vendido: 0,      ingresos_generados: 0 },
        { nombre: 'Leche Entera',            descripcion: '1 litro de leche entera de primera calidad.',                    fuenteImagen: '/images/productos/leche entera.webp',                precio: 950,        categoria: 'Bebidas',    subcategoria: 'Lacteos',                activo: 1,      valoracion_promedio: 0.00,      cantidad_valoraciones: 0,       cantidad_vendido: 0,      ingresos_generados: 0 },
        { nombre: 'Pan Integral',            descripcion: 'Pan artesanal integral, ideal para desayunos.',                  fuenteImagen: '/images/productos/pan.webp',                         precio: 800,        categoria: 'Comida',     subcategoria: 'Panaderia',              activo: 1,      valoracion_promedio: 0.00,      cantidad_valoraciones: 0,       cantidad_vendido: 0,      ingresos_generados: 0 },
        { nombre: 'Queso Cremoso',           descripcion: 'Queso fresco y suave, perfecto para untar.',                     fuenteImagen: '/images/productos/queso cremoso.jpg',                precio: 2500,       categoria: 'Comida',     subcategoria: 'Lacteos',                activo: 1,      valoracion_promedio: 0.00,      cantidad_valoraciones: 0,       cantidad_vendido: 0,      ingresos_generados: 0 },
        { nombre: 'Café Molido',             descripcion: 'Café premium 500g, aroma intenso y equilibrado.',                fuenteImagen: '/images/productos/cafe molido.webp',                 precio: 3200,       categoria: 'Bebidas',    subcategoria: 'Cafe',                   activo: 1,      valoracion_promedio: 4.50,      cantidad_valoraciones: 2,       cantidad_vendido: 0,      ingresos_generados: 0 },
        { nombre: 'Aceite de Oliva Virgen',  descripcion: 'Aceite de oliva 1L, ideal para ensaladas y cocina saludable.',   fuenteImagen: '/images/productos/aceite de oliva.jpg',              precio:  4500,      categoria: 'Comida',     subcategoria: 'Aceites y condimentos',  activo: 1,      valoracion_promedio: 0.00,      cantidad_valoraciones: 0,       cantidad_vendido: 0,      ingresos_generados: 0 },
        { nombre: 'Jugo de Naranja',         descripcion: 'Jugo natural de naranja 1L, sin conservantes.',                  fuenteImagen: '/images/productos/jugo de naranja.jpg',              precio:  1100,      categoria: 'Bebidas',    subcategoria: 'Jugos',                  activo: 1,      valoracion_promedio: 0.00,      cantidad_valoraciones: 0,       cantidad_vendido: 0,      ingresos_generados: 0 },
        { nombre: 'Agua Mineral',            descripcion: 'Botella de agua mineral 2L, pura y refrescante.',                fuenteImagen: '/images/productos/agua mineral.png',                 precio:   700,      categoria: 'Bebidas',    subcategoria: 'Agua',                   activo: 1,      valoracion_promedio: 0.00,      cantidad_valoraciones: 0,       cantidad_vendido: 0,      ingresos_generados: 0 },
        { nombre: 'Vino Tinto Malbec',       descripcion: 'Vino tinto Malbec 750ml, cosecha seleccionada.',                 fuenteImagen: '/images/productos/vino tinto malbec.webp',           precio:  5200,      categoria: 'Bebidas',    subcategoria: 'Vinos',                  activo: 1,      valoracion_promedio: 0.00,      cantidad_valoraciones: 0,       cantidad_vendido: 0,      ingresos_generados: 0 },
        { nombre: 'Remera Algodón',          descripcion: 'Remera básica de algodón 100%, cómoda y fresca.',                fuenteImagen: '/images/productos/remera algodon.jpg',               precio:  3500,      categoria: 'Ropa',       subcategoria: 'Prendas superiores',     activo: 1,      valoracion_promedio: 0.00,      cantidad_valoraciones: 0,       cantidad_vendido: 0,      ingresos_generados: 0 },
        { nombre: 'Pantalón Jeans',          descripcion: 'Pantalón de jean clásico azul, resistente y versátil.',          fuenteImagen: '/images/productos/jeans.webp',                       precio:  7200,      categoria: 'Ropa',       subcategoria: 'Prendas inferiores',     activo: 1,      valoracion_promedio: 0.00,      cantidad_valoraciones: 0,       cantidad_vendido: 0,      ingresos_generados: 0 },
        { nombre: 'Zapatillas Deportivas',   descripcion: 'Zapatillas livianas y transpirables, ideales para correr.',      fuenteImagen: '/images/productos/zapatillas deportivas.webp',       precio: 12500,      categoria: 'Ropa',       subcategoria: 'Calzado',                activo: 1,      valoracion_promedio: 0.00,      cantidad_valoraciones: 0,       cantidad_vendido: 0,      ingresos_generados: 0 },
        { nombre: 'Campera Abrigada',        descripcion: 'Campera acolchada para invierno, resistente al frío.',           fuenteImagen: '/images/productos/campera abrigo.jpg',               precio: 18500,      categoria: 'Ropa',       subcategoria: 'Prendas superiores',     activo: 1,      valoracion_promedio: 0.00,      cantidad_valoraciones: 0,       cantidad_vendido: 0,      ingresos_generados: 0 },
        { nombre: 'Detergente Líquido',      descripcion: 'Detergente concentrado para vajilla, elimina grasa fácilmente.', fuenteImagen: '/images/productos/detergente liquido.webp',          precio:   950,      categoria: 'Limpieza',   subcategoria: 'Cocina',                 activo: 1,      valoracion_promedio: 0.00,      cantidad_valoraciones: 0,       cantidad_vendido: 0,      ingresos_generados: 0 },
        { nombre: 'Lavandina',               descripcion: 'Lavandina clásica 2L, desinfecta y blanquea.',                   fuenteImagen: '/images/productos/lavandina.webp',                   precio:   750,      categoria: 'Limpieza',   subcategoria: 'Desinfectantes',         activo: 1,      valoracion_promedio: 0.00,      cantidad_valoraciones: 0,       cantidad_vendido: 0,      ingresos_generados: 0 },
        { nombre: 'Jabón en Polvo',          descripcion: 'Jabón en polvo para ropa, fragancia fresca.',                    fuenteImagen: '/images/productos/jabon en polvo.webp',              precio:  2100,      categoria: 'Limpieza',   subcategoria: 'Ropa',                   activo: 1,      valoracion_promedio: 0.00,      cantidad_valoraciones: 0,       cantidad_vendido: 0,      ingresos_generados: 0 },
        { nombre: 'Limpiador Multiuso',      descripcion: 'Limpiador multiuso con aroma cítrico, ideal para superficies.',  fuenteImagen: '/images/productos/limpiador multiuso.webp',          precio:  1300,      categoria: 'Limpieza',   subcategoria: 'Multiuso',               activo: 1,      valoracion_promedio: 0.00,      cantidad_valoraciones: 0,       cantidad_vendido: 0,      ingresos_generados: 0 },
        { nombre: 'Yogur Natural',           descripcion: 'Yogur cremoso sin azúcar, 200g.',                                fuenteImagen: '/images/productos/yogur natural.jpg',                precio:   600,      categoria: 'Bebidas',    subcategoria: 'Lacteos',                activo: 1,      valoracion_promedio: 0.00,      cantidad_valoraciones: 0,       cantidad_vendido: 0,      ingresos_generados: 0 },
        { nombre: 'Galletitas de Avena',     descripcion: 'Galletitas caseras con avena y miel.',                           fuenteImagen: '/images/productos/galletitas avena.webp',            precio:   900,      categoria: 'Comida',     subcategoria: 'Panaderia',              activo: 1,      valoracion_promedio: 0.00,      cantidad_valoraciones: 0,       cantidad_vendido: 0,      ingresos_generados: 0 },
        { nombre: 'Té Verde',                descripcion: 'Caja de 20 saquitos de té verde orgánico.',                      fuenteImagen: '/images/productos/te verde.jpg',                     precio:  1500,      categoria: 'Bebidas',    subcategoria: 'Infusiones',             activo: 1,      valoracion_promedio: 0.00,      cantidad_valoraciones: 0,       cantidad_vendido: 0,      ingresos_generados: 0 },
        { nombre: 'Hamburguesa Vegana',      descripcion: 'Hamburguesa vegetal a base de legumbres.',                       fuenteImagen: '/images/productos/hamburguesa vegana.jpeg',          precio:  2200,      categoria: 'Comida',     subcategoria: 'Vegano',                 activo: 1,      valoracion_promedio: 0.00,      cantidad_valoraciones: 0,       cantidad_vendido: 0,      ingresos_generados: 0 },
        { nombre: 'Miel Orgánica',           descripcion: 'Frasco de miel pura 500g.',                                      fuenteImagen: '/images/productos/miel organica.jpeg',               precio:  2800,      categoria: 'Comida',     subcategoria: 'Dulces',                 activo: 1,      valoracion_promedio: 0.00,      cantidad_valoraciones: 0,       cantidad_vendido: 0,      ingresos_generados: 0 },
        { nombre: 'Cerveza Artesanal',       descripcion: 'Botella de cerveza artesanal rubia 500ml.',                      fuenteImagen: '/images/productos/cerveza artesanal.webp',           precio:  1850,      categoria: 'Bebidas',    subcategoria: 'Cervezas',               activo: 1,      valoracion_promedio: 0.00,      cantidad_valoraciones: 0,       cantidad_vendido: 0,      ingresos_generados: 0 },
        { nombre: 'Shampoo Herbal',          descripcion: 'Shampoo natural con extracto de romero, 400ml.',                 fuenteImagen: '/images/productos/shampoo herbal.webp',              precio:  2300,      categoria: 'Higiene',    subcategoria: 'Cabello',                activo: 1,      valoracion_promedio: 0.00,      cantidad_valoraciones: 0,       cantidad_vendido: 0,      ingresos_generados: 0 },
        { nombre: 'Pasta Dental',            descripcion: 'Pasta dental con flúor, 90g.',                                   fuenteImagen: '/images/productos/pasta dental.jfif',                precio:  1200,      categoria: 'Higiene',    subcategoria: 'Oral',                   activo: 1,      valoracion_promedio: 0.00,      cantidad_valoraciones: 0,       cantidad_vendido: 0,      ingresos_generados: 0 },
        { nombre: 'Toallas de Algodón',      descripcion: 'Pack de 2 toallas suaves 70x140cm.',                             fuenteImagen: '/images/productos/toallas algodon.webp',             precio: 4800,       categoria: 'Hogar',      subcategoria: 'Baño',                   activo: 1,      valoracion_promedio: 0.00,      cantidad_valoraciones: 0,       cantidad_vendido: 0,      ingresos_generados: 0 },
        { nombre: 'Silla de Oficina',        descripcion: 'Silla ergonómica con respaldo ajustable.',                       fuenteImagen: '/images/productos/silla oficina.webp',               precio: 25000,      categoria: 'Hogar',      subcategoria: 'Muebles',                activo: 1,      valoracion_promedio: 0.00,      cantidad_valoraciones: 0,       cantidad_vendido: 0,      ingresos_generados: 0 },
        { nombre: 'Auriculares Bluetooth',   descripcion: 'Auriculares inalámbricos con micrófono integrado.',              fuenteImagen: '/images/productos/auriculares bluetooth.jpg',        precio: 8500,       categoria: 'Tecnologia', subcategoria: 'Audio',                  activo: 1,      valoracion_promedio: 0.00,      cantidad_valoraciones: 0,       cantidad_vendido: 0,      ingresos_generados: 0 },
        { nombre: 'Notebook 14"',            descripcion: 'Notebook liviana con 8GB RAM y SSD 256GB.',                      fuenteImagen: '/images/productos/notebook 14 pulgadas.jpg',         precio: 220000,     categoria: 'Tecnologia', subcategoria: 'Computadoras',           activo: 1,      valoracion_promedio: 0.00,      cantidad_valoraciones: 0,       cantidad_vendido: 0,      ingresos_generados: 0 },
        { nombre: 'Pelota de Fútbol',        descripcion: 'Pelota oficial tamaño 5, material sintético.',                   fuenteImagen: '/images/productos/pelota futbol.jpg',                precio: 6500,       categoria: 'Deportes',   subcategoria: 'Futbol',                 activo: 1,      valoracion_promedio: 0.00,      cantidad_valoraciones: 0,       cantidad_vendido: 0,      ingresos_generados: 0 },
    ];

    for (const producto of productos) {
        await cargarProducto(producto);
    }

    console.log('Datos completamente cargados en la tabla productos');
}


async function cargarProducto(producto)
{
    var existeProducto = await chequearExistenciaTablaSimple('productos', 'nombre', producto.nombre);

    if(existeProducto) console.log('ERROR: Ya existe el producto ' + producto.nombre);
    else
    {
        try
        {
            await conexionDB.query('INSERT INTO productos SET ?', producto);
            console.log('Se hizo el alta del producto: ' + producto.nombre);
        }
        catch(error) {console.log(error);}
    }
}

module.exports = { cargaDatosDePruebaTablaProductos };